application:
  port: 8000
database:
  database_name: "newsletter"
  password: "password"
  port: 5432
  username: "postgres"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
